# Generated by Django 4.2.5 on 2023-10-14 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_set_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='set',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='set',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='music.show'),
        ),
    ]
