# Generated by Django 4.2.6 on 2023-10-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_venue_show_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='abbreviation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
