# Generated by Django 4.2.6 on 2023-10-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_set_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
