# Generated by Django 4.2.6 on 2023-10-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_show_options_alter_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
